server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: stayhubadmin
    password: stayhubpass123
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

stripe:
  api-key: ${STRIPE_SECRET_KEY:sk_test_tu_clave_aqui}
